// Copyright Hola Games

#pragma once

#include "CoreMinimal.h"
#include "AuraNativeGameplayTag.h"
#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Vital_Health);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Vital_Mana);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Strength);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Intelligence);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Resilience);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Vigor);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_Armor);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_ArmorPenetration);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_BlockChance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_CriticalHitChance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_CriticalHitDamage);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_CriticalHitResistance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_HealthRegeneration);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_ManaRegeneration);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_MaxHealth);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Secondary_MaxMana);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Resistance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Resistance_FireResistance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Resistance_LightningResistance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Resistance_ArcaneResistance);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Resistance_PhysicalResistance);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LMB);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_RMB);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_1);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_2);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_3);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_4);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effects_HitReact);

extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Vital_Health;
extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Vital_Mana;

extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Primary_Strength;
extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Primary_Intelligence;
extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Primary_Resilience;
extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Primary_Vigor;

extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Secondary_Armor;
extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Secondary_ArmorPenetration;
extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Secondary_BlockChance;
extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Secondary_CriticalHitChance;
extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Secondary_CriticalHitDamage;
extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Secondary_CriticalHitResistance;
extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Secondary_HealthRegeneration;
extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Secondary_ManaRegeneration;
extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Secondary_MaxHealth;
extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Secondary_MaxMana;

extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Resistance;
extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Resistance_FireResistance;
extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Resistance_LightningResistance;
extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Resistance_ArcaneResistance;
extern AURA_API FAuraNativeGameplayTag TAG_Attributes_Resistance_PhysicalResistance;

extern AURA_API FAuraNativeGameplayTag TAG_InputTag_LMB;
extern AURA_API FAuraNativeGameplayTag TAG_InputTag_RMB;
extern AURA_API FAuraNativeGameplayTag TAG_InputTag_1;
extern AURA_API FAuraNativeGameplayTag TAG_InputTag_2;
extern AURA_API FAuraNativeGameplayTag TAG_InputTag_3;
extern AURA_API FAuraNativeGameplayTag TAG_InputTag_4;

// extern AURA_API FAuraNativeGameplayTag Tag_Damage;
// extern AURA_API FAuraNativeGameplayTag Tag_Damage_Fire;
// extern AURA_API FAuraNativeGameplayTag Tag_Damage_Lightning;
// extern AURA_API FAuraNativeGameplayTag Tag_Damage_Arcane;
// extern AURA_API FAuraNativeGameplayTag Tag_Damage_Physical;

extern AURA_API FAuraNativeGameplayTag TAG_Effects_HitReact;

/**
 * AuraGameplayTags
 *
 * Singleton containing native Gameplay Tags
 */
struct AURA_API FAuraGameplayTags
{
public:
	static const FAuraGameplayTags& Get()
	{
		if (!GameplayTags.bIsInitialized)
		{
			InitializeNativeGameplayTags();
		}
		return GameplayTags;
	}
	static void InitializeNativeGameplayTags();

	FGameplayTagContainer TagContainer = FGameplayTagContainer();

	static FGameplayTagContainer DamageTypes;
	static FGameplayTagContainer ResistanceTypes;
private:
	static bool bIsInitialized;
	static FAuraGameplayTags GameplayTags;
};